=== simplifica-if/base-conhecimento/base-conhecimento/schemas/cnct_curso.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/simplifica-if/base-conhecimento/main/schemas/cnct_curso.schema.json",
  "title": "Curso CNCT",
  "type": "object",
  "required": [
    "id",
    "indice",
    "denominacao",
    "denominacao_normalizada",
    "eixo_tecnologico",
    "area_tecnologica",
    "carga_horaria_minima_horas",
    "descricao_carga_horaria_minima",
    "perfil_profissional",
    "pre_requisitos_ingresso",
    "itinerarios_formativos",
    "campo_atuacao",
    "ocupacoes_cbo",
    "codigos_cbo",
    "infraestrutura_minima",
    "legislacao_profissional"
  ],
  "additionalProperties": false,
  "properties": {
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9]+(?:-[a-z0-9]+)*$"
    },
    "indice": {
      "type": "integer",
      "minimum": 1
    },
    "denominacao": {
      "type": "string",
      "minLength": 1
    },
    "denominacao_normalizada": {
      "type": "string",
      "pattern": "^[a-z0-9]+(?: [a-z0-9]+)*$"
    },
    "eixo_tecnologico": {
      "type": "string",
      "minLength": 1
    },
    "area_tecnologica": {
      "type": "string",
      "minLength": 1
    },
    "carga_horaria_minima_horas": {
      "type": "integer",
      "minimum": 1
    },
    "descricao_carga_horaria_minima": {
      "type": "string",
      "minLength": 1
    },
    "perfil_profissional": {
      "type": "string",
      "minLength": 1
    },
    "pre_requisitos_ingresso": {
      "type": "string",
      "minLength": 1
    },
    "itinerarios_formativos": {
      "type": "string",
      "minLength": 1
    },
    "campo_atuacao": {
      "type": "string",
      "minLength": 1
    },
    "ocupacoes_cbo": {
      "type": "string",
      "minLength": 1
    },
    "codigos_cbo": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^\\d{4}(?:-\\d{2})?$"
      }
    },
    "infraestrutura_minima": {
      "type": "string",
      "minLength": 1
    },
    "legislacao_profissional": {
      "type": "string",
      "minLength": 1
    }
  }
}

=== simplifica-if/base-conhecimento/catalogos/cnct/cursos/tecnico-em-eletromecanica.json
{
  "id": "tecnico-em-eletromecanica",
  "indice": 34,
  "denominacao": "Técnico em Eletromecânica",
  "denominacao_normalizada": "tecnico em eletromecanica",
  "eixo_tecnologico": "Controle e Processos Industriais",
  "area_tecnologica": "Eletrônica e Automação",
  "carga_horaria_minima_horas": 1200,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano e meio.\n\nO curso ofertado, na modalidade presencial, poderá prever até 20% da sua carga horária total em atividades não presenciais.\n\nO curso poderá ser realizado na modalidade EaD com, no mínimo, 20% de sua carga horária em atividades presenciais, nos termos das normas específicas definidas em cada sistema de ensino.\n\nA instituição, ofertante do curso, poderá desenvolver a carga horária em regime de alternância, com períodos de estudos na escola e outros períodos no campo/local de trabalho.\n\nAlém da carga horária mínima prevista, o curso poderá ter estágio curricular supervisionado obrigatório, a critério da instituição ofertante.\n\nCaso o curso seja ofertado na modalidade EaD, a carga horária de estágio deverá ser cumprida de forma presencial.",
  "perfil_profissional": "O Técnico em Eletromecânica será habilitado para:\n\nPlanejar, controlar e executar a instalação, a manutenção e a entrega técnica de máquinas e equipamentos eletromecânicos industriais, considerando as normas, os padrões e os requisitos técnicos de qualidade, saúde e segurança e de meio ambiente.\nElaborar projetos de produtos relacionados a máquinas e equipamentos eletromecânicos especificando materiais para construção mecânica e elétrica por meio de técnicas de usinagem e soldagem.\nRealizar inspeção visual, dimensional e testes em sistemas, instrumentos, equipamentos eletromecânicos, pneumáticos e hidráulicos de máquinas.\nReconhecer tecnologias inovadoras presentes no segmento visando a atender às transformações digitais na sociedade.\n\nPara atuação como Técnico em Eletromecânica, são fundamentais:\n\nConhecimentos e saberes relacionados aos processos de planejamento, produção e manutenção de equipamentos eletromecânicos de modo a assegurar a saúde e a segurança dos trabalhadores e dos usuários.\nConhecimentos e saberes relacionados à sustentabilidade do processo produtivo, às técnicas e aos processos de produção, às normas técnicas, à liderança de equipes, à solução de problemas técnicos e trabalhistas e à gestão de conflitos.",
  "pre_requisitos_ingresso": "Para ingresso no Curso Técnico Subsequente, o estudante deverá ter concluído o Ensino Médio.\nPara ingresso no Curso Técnico Concomitante, o estudante deverá estar cursando o Ensino Médio.\nPara ingresso no Curso Técnico Integrado ao Ensino Médio, o estudante deverá ter concluído o Ensino Fundamental.\nPara ingresso no Curso Técnico Integrado à Educação de Jovens e Adultos, o estudante deverá ter concluído o Ensino Fundamental.",
  "itinerarios_formativos": "Sugestões de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO:\n\nEletricista Predial de Baixa Tensão\nEletromecânico de Manutenção de Elevadores\nEletromecânico de Manutenção de Escadas Rolantes\nEletromecânico de Manutenção de Portas Automáticas\nMecânico de Manutenção de Máquinas\nMecânico de Fabricação\nOperador Eletromecânico\nInstalador de Sistemas Fotovoltaicos\n\nSugestões de formação continuada em cursos de especialização técnica (pós-técnico):\n\nEspecialização Técnica em Programação e Operação de Máquinas CNC\nEspecialização Técnica em Usinagem\nEspecialização Técnica em Desenho Assistido por Computador (CAD)\nEspecialização Técnica em Manufatura Assistida por Computador (CAM)\nEspecialização Técnica em Eficiência Energética em Edificações\nEspecialização Técnica em Eficiência Energética Industrial\nEspecialização Técnica em Energia Solar Fotovoltaica\nEspecialização Técnica em Energia Eólica\nEspecialização Técnica em Implantação e Comissionamento de Parques Eólicos\nEspecialização Técnica em Instalação Elétrica Predial de Baixa Tensão\nEspecialização Técnica em Biocombustíveis\nEspecialização Técnica em Biogás e Biometano\nEspecialização Técnica em Aproveitamento Energético de Biogás\n\nSugestões de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura):\n\nCurso Superior de Tecnologia em Automação Industrial\nCurso Superior de Tecnologia em Eletrônica Industrial\nCurso Superior de Tecnologia em Eletrotécnica Industrial\nCurso Superior de Tecnologia em Manutenção Industrial\nCurso Superior de Tecnologia em Mecatrônica Industrial\nCurso Superior de Tecnologia em Fabricação Mecânica\nCurso Superior de Tecnologia em Processos Metalúrgicos\nBacharelado em Engenharia Eletrônica\nBacharelado em Engenharia Elétrica\nBacharelado em Engenharia de Automação e Controle\nBacharelado em Engenharia Mecatrônica\nBacharelado em Engenharia Mecânica\nBacharelado em Engenharia de Produção\nBacharelado em Engenharia Metalúrgica",
  "campo_atuacao": "Locais e ambientes de trabalho:\n\nIndústrias com linhas de produção automatizadas, aeroespaciais, automobilística, metalmecânica e plástico\nEmpresas de manutenção e reparos eletromecânicos, que atuam na instalação, manutenção, comercialização e utilização de equipamentos e sistemas eletromecânicos",
  "ocupacoes_cbo": "3003-05 - Auxiliar Técnico de Instalações Eletromecânicas",
  "codigos_cbo": [
    "3003-05"
  ],
  "infraestrutura_minima": "Biblioteca com acervo físico ou virtual específico e atualizado\nLabotarório de informática com programas específicos\nLaboratório de eletricidade e eletrônica\nLaboratório de acionamentos elétricos\nLaboratório de máquinas elétricas\nLaboratório de instalações elétricas\nLaboratório de desenho técnico\nLaboratório de metrologia dimensional\nLaboratório de eletropneumática e eletro-hidráulica\nLaboratório de máquinas operatrizes (convencional e CNC/CAM)\nLaboratório de manutenção mecânica",
  "legislacao_profissional": "Lei nº 5.524, de 5 de novembro de 1968\nDecreto nº 90.922, de 6 de fevereiro de 1985\nDecreto nº 4.560, de 30 de dezembro de 2002\nResolução CFT nº 85, de 28 de outubro de 2019\nLei nº 13.639, de 26 de março de 2018\nResolução CFT nº 100, de 27 de abril de 2020\nResolução CFT nº 68, de 24 de maio de 2019\nResolução CFT nº 81, de 26 de outubro de 2019\nResolução CFT nº 121, de 14 de dezembro de 2020"
}

=== simplifica-if/base-conhecimento/catalogos/cnct/cursos/tecnico-em-paisagismo.json
{
  "id": "tecnico-em-paisagismo",
  "indice": 144,
  "denominacao": "Técnico em Paisagismo",
  "denominacao_normalizada": "tecnico em paisagismo",
  "eixo_tecnologico": "Produção Cultural e Design",
  "area_tecnologica": "Manifestações Artísticas",
  "carga_horaria_minima_horas": 1000,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano.\n\nO curso, na modalidade presencial, poderá prever até 20% da sua carga horária total em atividades não presenciais.\n\nO curso poderá ser realizado na modalidade EaD com, no mínimo, 20% de sua carga horária em atividades presenciais, nos termos das normas específicas definidas em cada sistema de ensino.\n\nA instituição, ofertante do curso, poderá desenvolver a carga horária em regime de alternância, com períodos de estudos na escola e outros períodos no campo de atuação/local de trabalho.\n\nAlém da carga horária mínima prevista, o curso poderá ter estágio curricular supervisionado obrigatório, a critério da instituição ofertante.\n\nCaso o curso seja ofertado na modalidade EaD, a carga horária de estágio deverá ser cumprida de forma presencial.",
  "perfil_profissional": "O Técnico em Paisagismo será habilitado para:\n\nElaborar e executar projetos de paisagismo.\nRealizar diagnóstico do local e apresentar propostas de intervenção, acompanhando o gerenciamento do projeto.\nOrganizar espaços de acordo com o projeto, respeitando o meio ambiente.\nAtuar na preservação e conservação de jardins de interesse patrimonial.\nElaborar representações gráficas bi e tridimensionais.\nEsboçar e definir especificidades e características de espaços, dos objetos e seus elementos.\nElaborar planos de trabalho que garantam a fidelidade na execução do projeto.\nProduzir plantas ornamentais.\nSupervisionar a manutenção de espaços de paisagismo, de jardins e de plantas ornamentais.\nGerenciar empreendimento paisagístico.\nZelar pela estética do produto (características plásticas, botânicas e ambientais), bem como zelar pelo respeito e preservação ambiental.\n\nPara atuação como Técnico em Paisagismo, são fundamentais:\n\nConhecimentos interdisciplinares relacionados aos processos de criação, envolvendo pesquisa, idealização, planejamento, execução técnica, fruição e recepção estética.\nCompetências comunicativas e empreendedoras voltadas à proposição de projetos, ao coletivo, à gestão, à solução de problemas e à resiliência, entre outras competências socioemocionais.",
  "pre_requisitos_ingresso": "Para ingresso no Curso Técnico Subsequente, o estudante deverá ter concluído o Ensino Médio.\nPara ingresso no Curso Técnico Concomitante, o estudante deverá estar cursando o Ensino Médio.\nPara ingresso no Curso Técnico Integrado ao Ensino Médio, o estudante deverá ter concluído o Ensino Fundamental.\nPara ingresso no Curso Técnico Integrado à Educação de Jovens e Adultos, o estudante deverá ter concluído o Ensino Fundamental.",
  "itinerarios_formativos": "Sugestões de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO:\n\nAuxiliar Geral de Conservação de Vias Permanentes (exceto trilhos)\nEditor de Maquetes Eletrônicas\nCadista para a Construção Civil\nAssistente de Jardinagem\n\nSugestões de formação continuada em cursos de especialização técnica (pós-técnico):\n\nEspecialização Técnica em Medições Topográficas\nEspecialização Técnica em Projetista de Maquetes Eletrônicas\nEspecialização Técnica em Vendas e Comercialização Vegetal\nEspecialização Técnica em Produção de Plantas Aromáticas e Medicinais\n\nSugestões de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura):\n\nCurso Superior de Tecnologia em Gestão Ambiental\nCurso Superior de Tecnologia em Design de Interiores\nBacharelado em Agronomia\nBacharelado em Arquitetura e Urbanismo\nBacharelado em Ciências Biológicas\nBacharelado em Engenharia Florestal",
  "campo_atuacao": "Locais e ambientes de trabalho:\n\nEscritórios de Design\nEscritórios de Projetos de Arquitetura e de Paisagismo\nEmpresas de Jardinagem\nProdução e Comercialização de Plantas Ornamentais\nConstrutoras, Imobiliárias e Órgãos Públicos\nProfissional Autônomo e Prestador de Serviços para elaboração e execução de projetos de paisagismo, bem como realização de diagnóstico e gerenciamento de projetos\nEmpreendimento Próprio\nInstituições Culturais e Museológicas na conservação e preservação de projetos paisagísticos de natureza patrimonial",
  "ocupacoes_cbo": "Ocupação ainda não classificada",
  "codigos_cbo": [],
  "infraestrutura_minima": "Biblioteca com acervo físico ou virtual específico e atualizado\nLaboratório de informática com programas específicos\nLaboratório jardim pedagógico\nLaboratório de desenho",
  "legislacao_profissional": "Lei nº 5.524, de 5 de novembro de 1968\nDecreto nº 90.922, de 6 de fevereiro de 1985"
}

=== simplifica-if/base-conhecimento/base-conhecimento/catalogos/cnct/cursos/tecnico-em-estrutura-e-pintura-de-aeronaves.json
{
  "id": "tecnico-em-estrutura-e-pintura-de-aeronaves",
  "indice": 198,
  "denominacao": "Técnico em Estrutura e Pintura de Aeronaves",
  "denominacao_normalizada": "tecnico em estrutura e pintura de aeronaves",
  "eixo_tecnologico": "Militar",
  "area_tecnologica": "Combate Aéreo",
  "carga_horaria_minima_horas": 1200,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano e meio.",
  "perfil_profissional": "O Técnico em Estrutura e Pintura de Aeronaves será habilitado, de acordo com cada Força, para:\n\nExecutar serviços de estrutura, de pintura e de manipulação de plásticos e de materiais não metálicos em aeronaves e seus componentes.\nMoldar e confeccionar gabaritos, fabricar peças metálicas, plásticas e similares.\nReparar peças de aeronaves e realizar reparos e construções em materiais compósitos.\nRealizar ensaios não destrutivos, controle e combate à corrosão e aplicação de selantes.",
  "pre_requisitos_ingresso": "Curso oferecido, exclusivamente, pela Marinha do Brasil e pela Força Aérea Brasileira aos militares do Serviço Ativo: o candidato deverá ter concluído o Ensino Médio e ser aprovado em processo seletivo das mencionadas Forças Armadas.",
  "itinerarios_formativos": "O curso não prevê sugestões de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO.\n\nSugestões de formação continuada em cursos de especialização técnica (pós-técnico):\n\nEspecialização Técnica em Mantenedor\nEspecialização Técnica em Inspetor\nEspecialização Técnica em Ensaios Não Destrutivos\n\nSugestões de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura):\n\nCurso Superior de Tecnologia em Manutenção de Aeronaves\nBacharelado em Engenharia Aeronáutica",
  "campo_atuacao": "Locais e ambientes de trabalho:\n\nMilitares da Ativa:\n\nExclusivamente em Organizações Militares da Aeronáutica\n\nMilitares da Reserva:\n\nEmpresas Aéreas e Oficinas de Manutenção Aeronáutica\nIndústria de Produtos Aeronáuticos\nMontadoras de Aeronaves\nEscolas e Centros de Instrução de Aviação\nEmpresas que prestam serviços aéreos especializados, aviação offshore, agrícola e outros",
  "ocupacoes_cbo": "7244-30 - Chapeador de Aeronaves\n7256-05 - Montador de Estruturas de Aeronaves",
  "codigos_cbo": [
    "7244-30",
    "7256-05"
  ],
  "infraestrutura_minima": "Biblioteca e videoteca com acervo específico e atualizado\nLaboratório de informática com programas específicos\nLaboratório de ensaios e corrosão\nLaboratório de desenho técnico\nLaboratório de materiais\nLaboratório específico de estrutura e pintura",
  "legislacao_profissional": "Padrão de Desempenho de Especialidade"
}

=== simplifica-if/base-conhecimento/base-conhecimento/catalogos/cnct/cursos/tecnico-em-transito.json
{
  "id": "tecnico-em-transito",
  "indice": 106,
  "denominacao": "Técnico em Trânsito",
  "denominacao_normalizada": "tecnico em transito",
  "eixo_tecnologico": "Infraestrutura",
  "area_tecnologica": "Operações de Transporte",
  "carga_horaria_minima_horas": 1000,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano e meio\n\nO curso, na modalidade presencial, poderá prever até 20% da sua carga horária total em atividades não presenciais.\n\nO curso poderá ser realizado na modalidade EaD com, pelo menos, 20% de sua carga horária em atividades presenciais, nos termos das normas específicas definidas em cada sistema de ensino.\n\nA instituição poderá desenvolver o curso em regime de alternância com períodos de estudo na escola e no campo de atuação/local de trabalho.\n\nAlém da carga horária mínima prevista, o curso poderá ter estágio curricular supervisionado obrigatório, a critério da instituição ofertante.\n\nCaso o curso seja ofertado na modalidade EaD, a carga horária de estágio será cumprida de forma presencial.",
  "perfil_profissional": "O Técnico em Trânsito será habilitado para:\n\nRealizar procedimentos de gestão, planejamento, fiscalização e operação do trânsito.\nPromover a educação e a segurança do trânsito.\nOrganizar a operação do tráfego urbano.\nOrganizar o controle da manutenção de equipamentos de tráfego, o monitoramento do trânsito e das vias públicas, a fiscalização de trânsito e de veículos.\nSupervisionar o cumprimento da legislação referente ao trânsito de veículos.\nRealizar pesquisas e tratamentos estatísticos de tráfego.\nSupervisionar operações de tráfego.\nRealizar estudos e implantação de melhorias para o trânsito nas vias rurais, nas cidades e em regiões metropolitanas.\n\nPara atuação como Técnico em Trânsito, são fundamentais:\n\nConhecimentos e saberes relacionados aos processos de gestão, planejamento, projeto, implantação e operação de atividades relacionadas ao transporte de passageiros, à logística e ao transporte de cargas.\nConhecimentos e saberes relacionados à educação e à segurança no trânsito; à engenharia de tráfego, assegurando a mobilidade urbana de acordo com as técnicas e processos; e às normas técnicas.\nHabilidades e competências relacionadas à liderança de equipes, à solução de problemas técnicos e trabalhistas e à gestão de conflitos.",
  "pre_requisitos_ingresso": "Para ingresso no Curso Técnico Subsequente, o estudante deverá ter concluído o Ensino Médio.\nPara ingresso no Curso Técnico Concomitante, o estudante deverá estar cursando o Ensino Médio.\nPara ingresso no Curso Técnico Integrado ao Ensino Médio, o estudante deverá ter concluído o Ensino Fundamental.\nPara ingresso no Curso Técnico Integrado à Educação de Jovens e Adultos, o estudante deverá ter concluído o Ensino Fundamental.",
  "itinerarios_formativos": "Sugestões de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO:\n\nSupervisor de Transportes\n\nSugestões de formação continuada em cursos de especialização técnica (pós-técnico):\n\nEspecialização Técnica em Educação e Segurança para o Trânsito\nEspecialização Técnica em Geoprocessamento\nEspecialização Técnica em Legislação Urbanística e de Mobilidade Urbana\nEspecialização Técnica em Simulações\n\nSugestões de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura):\n\nCurso Superior de Tecnologia em Estradas\nCurso Superior de Tecnologia em Transporte Terrestre\nBacharelado em Engenharia Civil\nBacharelado em Engenharia de Transportes\nBacharelado em Engenharia de Mobilidade",
  "campo_atuacao": "Locais e ambientes de trabalho:\n\nAgências reguladoras públicas de transporte\nConcessionárias rodoviárias e ferroviárias\nEmpresas de consultorias de projetos\nEmpresas de engenharia de tráfego\nEmpresas de logística\nOperadoras de transporte público\nOperadoras de transporte de cargas\nÓrgãos gestores de mobilidade urbana\nCentros de formação de condutores\nEmpresas de operação e gestão de vias urbanas\nEmpresas de sinalização viária",
  "ocupacoes_cbo": "3423-05 - Chefe de Serviço de Transporte Rodoviário (passageiros e cargas)\n3423-05 - Assistente de Tráfego Rodoviário\n3423-05 - Chefe de Departamento de Motoristas\n3423-05 - Chefe de Serviço de Transporte Rodoviário\n3423-05 - Coordenador de Tráfego Rodoviário\n3423-05 - Encarregado de Tráfego Rodoviário\n3423-05 - Gerente de Frota (transporte rodoviário)\n3423-05 - Programador de Transporte Rodoviário\n3423-10 - Inspetor de Serviços de Transportes Rodoviários (passageiros e cargas)",
  "codigos_cbo": [
    "3423-05",
    "3423-10"
  ],
  "infraestrutura_minima": "Biblioteca com acervo físico ou virtual específico e atualizado\nLaboratório de informática com programas específicos\nLaboratório de simulação de trânsito\nLaboratório de segurança e educação para o trânsito\nLaboratório de desenho",
  "legislacao_profissional": "Lei nº 5.524, de 5 de novembro de 1968\nDecreto nº 90.922, de 6 de fevereiro de 1985\nResolução CFT nº 85, de 28 de outubro de 2019"
}

=== simplifica-if/base-conhecimento/catalogos/cnct/cursos/tecnico-em-material-belico.json
{
  "id": "tecnico-em-material-belico",
  "indice": 202,
  "denominacao": "Técnico em Material Bélico",
  "denominacao_normalizada": "tecnico em material belico",
  "eixo_tecnologico": "Militar",
  "area_tecnologica": "Combate Aéreo",
  "carga_horaria_minima_horas": 1200,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano e meio.",
  "perfil_profissional": "O Técnico em Material Bélico será habilitado, de acordo com cada Força, para:\n\nExecutar procedimentos técnicos, prestar suporte e compor equipes multidisciplinares direcionadas às diversas tecnologias e equipamentos da área bélica, empregados em meios militares.\nExecutar serviços de tripulante operacional, metralhador em aeronaves, manutenção, pesquisa de avarias, reparos e aferição de equipamentos bélicos.\nExecutar serviços de artilheiro de bordo em aeronaves, manutenção, pesquisa de avarias, reparos e aferição de equipamentos bélicos.\nRealizar a instalação de assentos ejetáveis (FAB).\nArmar e desarmar aeronaves.\nIdentificar e prevenir corrosão em itens bélicos.\nRealizar a harmonização de sistemas de tiro e inventariar o sistema de lançamento de cargas nas aeronaves de combate.\nArmazenar e manejar itens bélicos ativos, controlando-os por meio de sistemas informatizados.",
  "pre_requisitos_ingresso": "Curso oferecido, exclusivamente, pela Marinha do Brasil e pela Força Aérea Brasileira aos militares do Serviço Ativo: o candidato deverá ter concluído o Ensino Médio e ser aprovado em processo seletivo das mencionadas Forças Armadas.",
  "itinerarios_formativos": "O curso não prevê sugestões de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO.\n\nSugestões de formação continuada em cursos de especialização técnica (pós-técnico):\n\nEspecialização Técnica em Manipulação de Material de Demolição\nEspecialização Técnica em Neutralização e Destruição de Artefatos Explosivos\nEspecialização Técnica em Atualização de Mantenedor em Material Bélico\nEspecialização Técnica em Inspetor de Material Bélico\nEspecialização em Manutenção em Assento Ejetável em Aeronave de Combate\nEspecialização em Aeronave de Combate de Asa Fixa e Asa Rotativa\n\nSugestões de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura), em ambiente externo à Marinha:\n\nCurso Superior de Tecnologia em Sistemas de Armas",
  "campo_atuacao": "Locais e ambientes do trabalho:\n\nMilitares da Ativa:\n\nExclusivamente em Organizações Militares da Marinha do Brasil e da Aeronáutica\n\nMilitares da Reserva:\n\nIndústrias de Material Bélico",
  "ocupacoes_cbo": "9502-05 - Encarregado de Manutenção Elétrica de Veículos\n9144-05 - Mecânico de Manutenção de Automóveis, Motocicletas e Veículos Similares\n9144-25 - Mecânico de Veículos Automotores a Diesel (exceto tratores)\n9502-05 - Encarregado de Manutenção Elétrica de Veículos",
  "codigos_cbo": [
    "9502-05",
    "9144-05",
    "9144-25"
  ],
  "infraestrutura_minima": "Biblioteca e videoteca com acervo específico e atualizado\nLaboratório de informática com programas atualizados\nLaboratório de eletricidade e eletrônica\nLaboratório de hidráulica e pneumática\nLaboratório de manutenção mecânica\nLaboratório específico de guarda e segurança",
  "legislacao_profissional": "Padrão de Desempenho de Especialidade\nCatálogo de Referenciais de Competências Profissionais (CR) da Marinha do Brasil"
}

=== simplifica-if/base-conhecimento/catalogos/cnct/cursos/tecnico-em-hidrografia.json
{
  "id": "tecnico-em-hidrografia",
  "indice": 208,
  "denominacao": "Técnico em Hidrografia",
  "denominacao_normalizada": "tecnico em hidrografia",
  "eixo_tecnologico": "Militar",
  "area_tecnologica": "Combate Naval",
  "carga_horaria_minima_horas": 1200,
  "descricao_carga_horaria_minima": "O curso dura, em média, 1 ano e meio.",
  "perfil_profissional": "O Técnico em Hidrografia será habilitado para:\n\nColetar dados meteorológicos, maregráficos, oceanográficos, hidrográficos, geológicos, por meio da operação de equipamentos específicos.\nInterpretar boletins meteorológicos.\nConfeccionar cartas náuticas oceânicas e de vias navegáveis interiores, sob supervisão profissional pertinente.\nEfetuar medições em campo para execução dos métodos topográfico-altimétricos.\nRealizar cálculos topográficos.\nIdentificar astros e elementos que determinam sua posição na esfera celeste.\nDeterminar a posição de um navio por meio de métodos específicos.\nOrientar equipes nas tarefas de medição de ângulos, observação e cálculos de marés.\nOperar sistemas de geoprocessamento.",
  "pre_requisitos_ingresso": "Curso oferecido, exclusivamente, pela Marinha do Brasil aos militares do Serviço Ativo: o candidato deverá ter concluído o Ensino Médio e ser aprovado em processo seletivo da mencionada Força Armada.",
  "itinerarios_formativos": "O curso não prevê possibilidade de qualificação profissional com certificações intermediárias, no curso técnico, considerando ocupações previstas na CBO.\n\nO curso não prevê possibilidade de formação continuada em cursos de especialização técnica (pós-técnico).\n\nO curso não prevê possibilidade de verticalização para cursos de graduação (Curso Superior de Tecnologia, Bacharelado e Licenciatura) no âmbito da Marinha.",
  "campo_atuacao": "Locais e ambientes do trabalho:\n\nMilitares da Ativa:\n\nExclusivamente nas Organizações Militares da Marinha do Brasil\n\nMilitares da Reserva:\n\nAdministrações Portuárias\nEmpresas de construção ou consultoria, que realizem trabalhos de hidráulica marítima ou fluvial\nEmpresas de construção civil\nEmpresas de navegação mercante e de pesca",
  "ocupacoes_cbo": "3123-15 - Técnico em Hidrografia",
  "codigos_cbo": [
    "3123-15"
  ],
  "infraestrutura_minima": "Biblioteca e videoteca com acervo específico e atualizado\nLaboratório de informática com programas específicos\nLaboratório de dados oceanográficos\nLaboratório de meteorologia\nLaboratório de topografia e geodésia\nLaboratório de geoprocessamento",
  "legislacao_profissional": "Catálogo de Referenciais de Competências Profissionais (CR) da Marinha do Brasil"
}
